site_name: F Prime
site_url: https://fprime.jpl.nasa.gov/
repo_url: https://github.com/nasa/fprime
repo_name: nasa/fprime

theme:
  name: material # enables the material theme, DO NOT CHANGE
  language: en
  logo: assets/images/logo-fprime-jpl.svg
  favicon: assets/images/favicon.svg
  custom_dir: docs/overrides
  icon:
    annotation: material/information-slab-circle  # custom icon for annotations

  features:
    - navigation.tabs # enables tabs
    - navigation.top # enables back to top button
    - navigation.tabs.sticky # makes tabs sticky
    # - navigation.expand # expands all navigation links with dropdowns by default
    - navigation.footer # enables previous/next page navigation links by the footer
    - navigation.instant # instant loading
    - navigation.indexes # enables overview pages for sections
    - navigation.tracking # URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents
    - content.code.copy # enable code copy for all code blocks
    - content.code.annotate # enable code annotations for all code blocks
    - content.tooltips # replaces the browser's rendering logic for title attribute with tooltips (for content, header, navigation)
    - content.tabs.link # all content tabs across the whole documentation site will be linked and switch to the same label when the user clicks on a tab

  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-off
        name: Switch to light mode



# Adds extra settings
extra:
  version:
      provider: mike
      alias: true
  generator: false # removes "Made with Material for Mkdocs"




# Link to custom css
extra_css:
  - assets/stylesheets/extra.css

# Adds material for mkdocs plugins
plugins:
  - search # enables search
  - mike:
      # symlink are not allowed in our usage of GH Pages so we have to use copy
      # see https://github.blog/changelog/2023-02-21-github-pages-deprecating-symlinks-in-non-actions-builds/
      alias_type: copy
      canonical_version: latest
      deploy_prefix: fprime
  - open-in-new-tab
  - multirepo:
      cleanup: true
      nav_repos:
        - name: tutorials-hello-world
          import_url: https://github.com/fprime-community/fprime-tutorial-hello-world?branch=devel
          imports: [
            docs/hello-world.md
          ]
        - name: tutorials-led-blinker
          import_url: https://github.com/fprime-community/fprime-workshop-led-blinker?branch=devel
          imports: [
            docs/led-blinker.md,
            docs/hardware.md
            docs/img
          ]
        - name: tutorials-math-component
          import_url: https://github.com/fprime-community/fprime-tutorial-math-component?branch=devel
          imports: [
            docs/math-component.md
            docs/img
          ]
        - name: tutorials-arduino-led-blinker
          import_url: https://github.com/fprime-community/fprime-tutorial-arduino-blinker?branch=main
          imports: [
            docs/arduino-led-blinker.md,
            docs/img
          ]


markdown_extensions: 
  - toc:
      toc_depth: 2
  - attr_list # allows to add HTML attributes and CSS classes to almost every Markdown inline- and block-level element with a special syntax
  - md_in_html # allows for writing Markdown inside of HTML
  - tables # enables markdown tables
  # enables syntax highlighting on code blocks and inline code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  # adds support for admonitions/call-outs
  - admonition
  - pymdownx.details
  - github-callouts # enables GitHub-style Markdown alerts (e.g. > [!NOTE])
  # enables the use of definition lists and tasks lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # enables abbreviations and allows to build a simple project-wide glossary, sourcing definitions from a central location.
  - abbr
  - pymdownx.snippets
  # enables tabs
  - pymdownx.tabbed:
      alternate_style: true
  # enables the use of icons and emojis by using simple shortcodes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg




# Custom navigation
nav:
  - Home: 'https://github.jpl.nasa.gov/pages/ashleysa/fprime-website-mkdocs/'
  - Overview: 'https://github.jpl.nasa.gov/pages/ashleysa/fprime-website-mkdocs/overview/'
  - Getting Started: 
    - getting-started/index.md
    - 'Installation and Troubleshooting': getting-started/installing-fprime.md
  - Documentation:
    - documentation/index.md
    - Tutorials:
      - 'Tutorials Overview': documentation/tutorials/index.md
      - 'Hello World': tutorials-hello-world/docs/hello-world.md
      - 'LED Blinker': tutorials-led-blinker/docs/led-blinker.md
      - 'MathComponent': tutorials-math-component/docs/math-component.md
      - 'Cross-Compilation Setup': documentation/tutorials/cross-compilation.md
      - 'Arduino LED Blinker': tutorials-arduino-led-blinker/docs/arduino-led-blinker.md
    - User Manual:
      - documentation/user-manual/index.md
      - Overview:
        - 'Introduction to F´': documentation/user-manual/overview/full-intro.md
        - 'The F´ Ground Data System': documentation/user-manual/overview/gds-introduction.md
        - 'F´ Development Process': documentation/user-manual/overview/development-practice.md
        - 'A Tour of the Source Tree': documentation/user-manual/overview/source-tree.md
        - 'Projects and Deployments': documentation/user-manual/overview/proj-dep.md
        - 'Core Constructs: Ports, Components, and Topologies': documentation/user-manual/overview/port-comp-top.md
        - 'Data Constructs': documentation/user-manual/overview/cmd-evt-chn-prm.md
        - 'Data Types and Data Structures': documentation/user-manual/overview/enum-arr-ser.md
        - 'Unit Testing F´ Components': documentation/user-manual/overview/unit-testing.md
      - Framework:
        - 'Configuring F´': documentation/user-manual/framework/configuring-fprime.md
        - 'Autocoded Functions': documentation/user-manual/framework/autocoded-functions.md
        - 'Constructing the F´ Topology': documentation/user-manual/framework/building-topology.md
        - 'Asserts in F´': documentation/user-manual/framework/assert.md
        - 'F´ On Baremetal and Multi-Core Systems': documentation/user-manual/framework/baremetal-multicore.md
        - 'Application, Manager, Driver Pattern': documentation/user-manual/framework/app-man-drv.md
        - 'Ground Interface': documentation/user-manual/framework/ground-interface.md
        - 'Dynamic Memory and Buffer Management': documentation/user-manual/framework/dynamic-memory.md
        - 'The Hub Pattern': documentation/user-manual/framework/hub-pattern.md
        - 'settings.ini: Build Settings Configuration': documentation/user-manual/framework/settings.md
        - 'The F´ CMake Build System': documentation/user-manual/cmake/cmake-intro.md
      - 'FPP': 'https://nasa.github.io/fpp/fpp-users-guide.html'
      - GDS:
        - "The GDS CLI": documentation/user-manual/gds/gds-cli.md
        - 'The GDS Dashboard': documentation/user-manual/gds/gds-custom-dashboards.md
        - 'GDS Dashboard Reference': documentation/user-manual/gds/gds-dashboard-reference.md
        - 'Integration Test API': documentation/user-manual/gds/gds-test-api-guide.md
        - 'Sequencing in F´': documentation/user-manual/gds/seqgen.md
      - Design:
        - 'F´ Software Architecture': documentation/user-manual/design/fprime-architecture.md
        - 'Numerical Types Design': documentation/user-manual/design/numerical-types.md
        - 'Communication Adapter Interface': documentation/user-manual/design/communication-adapter-interface.md
        - 'Package Implementations': documentation/user-manual/design/package-implementations.md
        - 'FPP JSON Dictionary Specification': documentation/user-manual/design/fpp-json-dict.md
        - 'Rate Groups and Timeliness': documentation/user-manual/design/rate-group.md
        - 'F´ Data Products': documentation/user-manual/design/data-products.md
    - How To: 
      - documentation/how-to/index.md
      - 'F´ Library Development': documentation/how-to/develop-fprime-libraries.md
      - 'F´ Subtopology Development': documentation/how-to/develop-subtopologies.md
      - 'F´ GDS Plugin Development': documentation/how-to/develop-gds-plugins.md
      - 'Porting F´ To a New Platform': documentation/how-to/porting-guide.md
    - Reference:
      - documentation/reference/index.md
      - 'C++ Documentation': 'documentation/reference/api/cpp/html/index.html'
      - 'FPP Language Specification': https://nasa.github.io/fpp/fpp-spec.html
      - 'CMake User API': 'documentation/user-manual/cmake/cmake-api.md'
      - 'GDS Developers Guide': documentation/reference/gds-cli-dev.md
  - Support: 'https://github.jpl.nasa.gov/pages/ashleysa/fprime-website-mkdocs/support'
  - Events: 'https://github.jpl.nasa.gov/pages/ashleysa/fprime-website-mkdocs/events'